name: Build plugin

on:
  push:
    tags:
      - '*'

jobs:
  plugin-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-amd64-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-amd64-

      - name: Install dependencies
        run: go mod tidy

      - name: build all
        run: make tar-amd64 COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: polarity-ecs-ebs-plugin.amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  plugin-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-arm64-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-arm64-

      - name: Install dependencies
        run: go mod tidy

      - name: build all
        run: make tar-arm64 COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: polarity-ecs-ebs-plugin.arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
