name: Build plugin

on:
  push:
    branches:
      - main

jobs:
  plugin-amd64:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-amd64-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-amd64-

      - name: Install dependencies
        run: go mod tidy

      - name: build all
        run: make tar-amd64 COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload tarball to S3
        env:
          CODE_BUCKET: ${{ secrets.CODE_BUCKET }}
        run: |
          aws s3 cp polarity-ecs-ebs-plugin.amd64.tar.gz s3://${CODE_BUCKET}/releases/${{ github.sha }}/amd64/polarity-ecs-ebs-plugin.tar.gz
          aws s3 cp polarity-ecs-ebs-plugin.amd64.tar.gz s3://${CODE_BUCKET}/releases/latest/amd64/polarity-ecs-ebs-plugin.tar.gz

  plugin-arm64:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-arm64-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-arm64-

      - name: Install dependencies
        run: go mod tidy

      - name: build all
        run: make tar-arm64 COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload tarball to S3
        env:
          CODE_BUCKET: ${{ secrets.CODE_BUCKET }}
        run: |
          aws s3 cp polarity-ecs-ebs-plugin.arm64.tar.gz s3://${CODE_BUCKET}/releases/${{ github.sha }}/arm64/polarity-ecs-ebs-plugin.tar.gz
          aws s3 cp polarity-ecs-ebs-plugin.arm64.tar.gz s3://${CODE_BUCKET}/releases/latest/arm64/polarity-ecs-ebs-plugin.tar.gz
